"""
synthesizer.py — CTGAN Model Training and Synthetic Data Generation.

Uses CTGANSynthesizer from SDV to train on minority class (fraud) samples
and generate synthetic fraud data to balance the dataset.
"""

import os
import pandas as pd
import numpy as np
from sdv.single_table import CTGANSynthesizer
from sdv.metadata import SingleTableMetadata


def create_metadata(fraud_df):
    """
    Create SDV metadata from the fraud DataFrame.

    Parameters
    ----------
    fraud_df : pd.DataFrame
        DataFrame containing only fraud samples (Class=1).

    Returns
    -------
    SingleTableMetadata
        Metadata object for SDV.
    """
    metadata = SingleTableMetadata()
    metadata.detect_from_dataframe(fraud_df)
    print("Metadata detected successfully.")
    print(f"Columns: {list(fraud_df.columns)}")
    return metadata


def train_ctgan(fraud_df, epochs=300, verbose=True):
    """
    Train a CTGANSynthesizer on fraud samples.

    Parameters
    ----------
    fraud_df : pd.DataFrame
        DataFrame containing only fraud samples.
    epochs : int
        Number of training epochs. Default is 300 as per project spec.
    verbose : bool
        Whether to print progress updates during training.

    Returns
    -------
    CTGANSynthesizer
        The trained synthesizer model.
    """
    print("=" * 60)
    print("CTGAN TRAINING")
    print("=" * 60)
    print(f"Training samples: {len(fraud_df)}")
    print(f"Features: {len(fraud_df.columns)}")
    print(f"Epochs: {epochs}")
    print("-" * 60)

    # Create metadata
    metadata = create_metadata(fraud_df)

    # Initialize and train the synthesizer
    print("\nInitializing CTGANSynthesizer...")
    synthesizer = CTGANSynthesizer(
        metadata,
        epochs=epochs,
        verbose=verbose
    )

    print("Starting training... (this may take several minutes)")
    synthesizer.fit(fraud_df)
    print("\nTraining complete!")

    return synthesizer


def generate_samples(synthesizer, num_rows):
    """
    Generate synthetic fraud samples using the trained synthesizer.

    Parameters
    ----------
    synthesizer : CTGANSynthesizer
        The trained CTGAN model.
    num_rows : int
        Number of synthetic samples to generate.

    Returns
    -------
    pd.DataFrame
        DataFrame containing synthetic fraud samples.
    """
    print(f"\nGenerating {num_rows} synthetic fraud samples...")
    synthetic_samples = synthesizer.sample(num_rows=num_rows)
    print(f"Generated {len(synthetic_samples)} synthetic samples successfully.")

    # Ensure Class column is 1 for all synthetic samples
    if "Class" in synthetic_samples.columns:
        synthetic_samples["Class"] = 1

    return synthetic_samples


def save_synthetic_data(synthetic_df, filename="synthetic_fraud_samples.csv"):
    """
    Save synthetic data to CSV in the outputs directory.

    Parameters
    ----------
    synthetic_df : pd.DataFrame
        Synthetic fraud samples.
    filename : str
        Output filename.

    Returns
    -------
    str
        Path to the saved file.
    """
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    outputs_dir = os.path.join(project_root, "outputs")
    os.makedirs(outputs_dir, exist_ok=True)

    save_path = os.path.join(outputs_dir, filename)
    synthetic_df.to_csv(save_path, index=False)
    print(f"Synthetic data saved to: {save_path}")

    return save_path


def create_balanced_dataset(original_df, synthetic_df):
    """
    Combine the original dataset with synthetic fraud samples to create a balanced dataset.

    Parameters
    ----------
    original_df : pd.DataFrame
        The original full dataset (imbalanced).
    synthetic_df : pd.DataFrame
        Synthetic fraud samples generated by CTGAN.

    Returns
    -------
    pd.DataFrame
        The balanced dataset.
    """
    # Combine original data with synthetic fraud samples
    balanced_df = pd.concat([original_df, synthetic_df], ignore_index=True)

    # Shuffle the dataset
    balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

    # Print new class distribution
    class_counts = balanced_df["Class"].value_counts()
    print("\n" + "=" * 60)
    print("BALANCED DATASET CREATED")
    print("=" * 60)
    print(f"Total samples: {len(balanced_df)}")
    print(f"Non-Fraud (0): {class_counts.get(0, 0)}")
    print(f"Fraud (1):     {class_counts.get(1, 0)}")
    print(f"New ratio:     {class_counts.get(0, 0) / max(class_counts.get(1, 0), 1):.2f}:1")

    # Save balanced dataset
    save_path = save_synthetic_data(balanced_df, filename="balanced_dataset.csv")

    return balanced_df


def calculate_target_count(original_df):
    """
    Calculate how many synthetic fraud samples are needed to balance the dataset.

    Parameters
    ----------
    original_df : pd.DataFrame
        The original dataset.

    Returns
    -------
    int
        Number of synthetic samples needed.
    """
    non_fraud_count = (original_df["Class"] == 0).sum()
    fraud_count = (original_df["Class"] == 1).sum()
    target_count = non_fraud_count - fraud_count

    print(f"Non-fraud samples: {non_fraud_count}")
    print(f"Existing fraud samples: {fraud_count}")
    print(f"Synthetic samples needed for balance: {target_count}")

    return target_count
